import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Listing } from '../types';

function triggerDownload(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

// --- CSV and XLS Export ---
function escapeCsvCell(cell: any): string {
    const cellStr = String(cell ?? '');
    // If the cell contains a comma, double quote, or newline, wrap it in double quotes
    if (/[",\n]/.test(cellStr)) {
        // Within a quoted field, double quotes must be escaped by another double quote
        return `"${cellStr.replace(/"/g, '""')}"`;
    }
    return cellStr;
}

function convertToCsv(data: Listing[]): string {
    const headers = [
        'ID', 'Created At', 'Title', 'Description', 'Selected Price', 'Category', 
        'Price Suggestion (Quick Sale)', 'Price Suggestion (Market Value)', 'Price Suggestion (Premium)', 'Price Justification',
        'eBay Title', 'eBay HTML Description', 'Twitter Tweet'
    ];
    
    const rows = data.map(listing => [
        listing.id,
        listing.createdAt,
        listing.title,
        listing.description,
        listing.selectedPrice,
        listing.category,
        listing.priceSuggestion.quickSale,
        listing.priceSuggestion.marketValue,
        listing.priceSuggestion.premium,
        listing.priceSuggestion.justification,
        listing.ebay?.title,
        listing.ebay?.descriptionHtml,
        listing.twitter?.tweet,
    ].map(escapeCsvCell));

    return [headers.join(','), ...rows.map(row => row.join(','))].join('\n');
}

export const exportAsCsv = (data: Listing[], xls = false) => {
    const csvString = convertToCsv(data);
    const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
    triggerDownload(blob, `listings.${xls ? 'xls' : 'csv'}`);
};


// --- PDF Export ---
export const exportAsPdf = (data: Listing[]) => {
    const doc = new jsPDF({ orientation: 'landscape' });
    
    const formatCurrency = (price: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(price);

    const tableData = data.map(listing => [
        listing.title,
        listing.category,
        formatCurrency(listing.selectedPrice),
        listing.priceSuggestion.justification,
        new Intl.DateTimeFormat('en-US').format(new Date(listing.createdAt)),
    ]);

    autoTable(doc, {
        head: [['Title', 'Category', 'Selected Price', 'Pricing Rationale', 'Date']],
        body: tableData,
        didDrawPage: (data) => {
            doc.setFontSize(20);
            doc.text('Marketplace Listings', data.settings.margin.left, 15);
        },
        styles: {
            fontSize: 8,
            cellPadding: 2,
        },
        headStyles: {
            fillColor: [30, 41, 59], // slate-800
        },
        columnStyles: {
            0: { cellWidth: 50 },
            1: { cellWidth: 25 },
            2: { cellWidth: 25 },
            3: { cellWidth: 'auto' },
            4: { cellWidth: 25 },
        }
    });

    doc.save('listings.pdf');
};


// --- SQL Export ---
function escapeSqlValue(value: any): string {
    if (value === null || typeof value === 'undefined') {
        return 'NULL';
    }
    if (typeof value === 'number') {
        return String(value);
    }
    // Escape single quotes by doubling them up
    return `'${String(value).replace(/'/g, "''")}'`;
}

export const exportAsSql = (data: Listing[]) => {
    let sqlString = `
-- Generated by AI Listing Generator
-- Dropping and creating the table
DROP TABLE IF EXISTS listings;
CREATE TABLE listings (
    id VARCHAR(255) PRIMARY KEY,
    createdAt TIMESTAMP,
    title TEXT,
    description TEXT,
    selectedPrice DECIMAL(10, 2),
    category VARCHAR(255),
    priceSuggestionQuickSale DECIMAL(10, 2),
    priceSuggestionMarketValue DECIMAL(10, 2),
    priceSuggestionPremium DECIMAL(10, 2),
    priceJustification TEXT,
    ebayTitle TEXT,
    ebayDescriptionHtml TEXT,
    twitterTweet TEXT
);

-- Inserting data
`;

    data.forEach(listing => {
        const values = [
            escapeSqlValue(listing.id),
            escapeSqlValue(listing.createdAt),
            escapeSqlValue(listing.title),
            escapeSqlValue(listing.description),
            escapeSqlValue(listing.selectedPrice),
            escapeSqlValue(listing.category),
            escapeSqlValue(listing.priceSuggestion.quickSale),
            escapeSqlValue(listing.priceSuggestion.marketValue),
            escapeSqlValue(listing.priceSuggestion.premium),
            escapeSqlValue(listing.priceSuggestion.justification),
            escapeSqlValue(listing.ebay?.title),
            escapeSqlValue(listing.ebay?.descriptionHtml),
            escapeSqlValue(listing.twitter?.tweet),
        ].join(', ');
        
        sqlString += `INSERT INTO listings (id, createdAt, title, description, selectedPrice, category, priceSuggestionQuickSale, priceSuggestionMarketValue, priceSuggestionPremium, priceJustification, ebayTitle, ebayDescriptionHtml, twitterTweet) VALUES (${values});\n`;
    });
    
    const blob = new Blob([sqlString], { type: 'application/sql;charset=utf-t;' });
    triggerDownload(blob, 'listings.sql');
};
